language: node_js
node_js:
- node
- 8
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: CyQNcYqiUoK75DPpzddamNkqcfnVrcIJ5ccGz8vXiU88bwXKfZGrKknu5uB+W4ZBe3aqvJVrycz0Q6bmyg/PXVfy/yUcVqXOGLqOjhO2zWIUk1Dmc7AuRcNf7JjsoenZjjSMJBgh8zkfGJAYkRR9XvB80+K/+xqreGtJb8dOwBwEVqUmkjcneKYlogoWwg2EA7WpqulwZTUyTJMwEF2YfRpocXUDUXbJG7J7pX+QS6I8BZL/el7IuHlzoPJE2elp9+5mga0aCtNaVvHQhjyzwngS9Be0C1l+yAZNAYI37HJqrk+ZMylJPrNOF2momvwf4rqhAbvFrxe+fHDrmWiCPGpftPgxc+XQ5/snxFn6V0EuyvFabud1NmFiGZdMWBStoPg64lYxuVoAZUCM+TzBXKjYXr5VjL2o9B/14ODQtSDP9pLX/NDCcapEyIqtkEM5PJzC6yNYo8eqVSZA9lT1s6c0iMcSmmrCpBNAlNAz0O4HVHz1IZ/RcEhkbaudYshXofwAmpg/hrnlc3VcM0mAXIdDxl0CNlr0pfUofuwN74egy+PnOk1S6PgMdnyQAYe8Web98Fy67/Ude70vQLdVPpC6n+wy4avwJSDuib19Atfi1PsKHUqCybe9X6yZNmP5ryvfbAATXVmG0i12/63/Q/I/lsQPfSD2DTapm1VnxUQ=
  on:
    tags: true
    repo: xogroup/origami-logs
